# Configuration file for tc-worker.Dockerfile
transforms:
  - env
  - secrets
  - packet
config:
  credentials:
    # Taskcluster credentials with scopes like:
    # - assume:project:taskcluster:worker-test-scopes
    # - secrets:get:project/taskcluster/taskcluster-worker/stateless-dns
    clientId:       {$env: TASKCLUSTER_CLIENT_ID}
    accessToken:    {$env: TASKCLUSTER_ACCESS_TOKEN}
  engine:           {$env: ENGINE}
  engines:
    native:
      createUser:     false
    qemu:
      limits:
        defaultThreads: 1
        maxCPUs:        2
        maxMemory:      4096
      network:
        subnets:      2
  minimumDiskSpace:   10000000  # 10 GB
  minimumMemory:      1000000   # 1 GB
  monitor:
    logLevel:       debug
    project:        test-dummy-worker
  plugins:
    disabled:       [reboot]
    interactive:    {}
    artifacts:      {}
    env:            {}
    livelog:        {}
    logprefix:      {}
    tcproxy:        {}
    maxruntime:
      maxRunTime:   '1 hour'
      perTaskLimit: 'allow'
    success:        {}
  temporaryFolder:  /mnt/tmp
  webHookServer:
    provider:           stateless-dns
    expiration:         '1 day'
    serverIp:           {$packet: public-ipv4}
    serverPort:         {$env: PORT, type: number}
    networkInterface:   eth0
    exposedPort:        {$env: PORT, type: number}
    tlsCertificate:
      $secret:  project/taskcluster/taskcluster-worker/stateless-dns
      key:      certificate
    tlsKey:
      $secret:  project/taskcluster/taskcluster-worker/stateless-dns
      key:      tlsKey
    statelessDNSSecret:
      $secret:  project/taskcluster/taskcluster-worker/stateless-dns
      key:      secret
    statelessDNSDomain:
      $secret:  project/taskcluster/taskcluster-worker/stateless-dns
      key:      domain
  worker:
    concurrency:          2
    minimumReclaimDelay:  30
    pollingInterval:      5
    reclaimOffset:        300
    provisionerId:        {$env: PROVISIONER_ID}
    workerType:           {$env: WORKER_TYPE}
    workerGroup:          {$env: WORKER_GROUP}
    workerId:             {$env: WORKER_ID}
