#cloud-config
coreos:
  # The following variables must be filled out:
  #   papertrail log destination: <log-host> <log-port>
  #   taskcluster credentials: <client-id> <access-token>
  # Then this is ready to go!
  units:
    # Disable SSH
    - name:    sshd.socket
      mask:    true
      command: stop
    - name:    sshd.service
      mask:    true
      command: stop
    # Stop updates of coreos
    - name:    locksmithd.service
      mask:    true
      command: stop
    # Disable fleet socket activation
    - name:    fleet.socket
      mask:    true
      command: stop
    # Disable etcd2
    - name:    etcd2.service
      mask:    true
      command: stop
    # Enable debug-level logging
    - name:    systemd-journald.service
      command: restart
      drop-ins:
        - name: 10-debug.conf
          content: |
            [Service]
            Environment=SYSTEMD_LOG_LEVEL=debug
    # Setup logging to papertrail
    - name:    papertrail.service
      command: start
      content: |
        [Unit]
        Description=forward syslog to papertrail
        After=systemd-journald.service
        Before=docker.service
        Requires=systemd-journald.service

        [Service]
        ExecStart=/bin/sh -c "journalctl -f | ncat --ssl <log-host> <log-port>"
        TimeoutStartSec=0
        Restart=on-failure
        RestartSec=5s
    # Reload kvm_intel with nested virtualization allowed
    - name:    kvm_intel_nested.service
      command: start
      content: |
        [Unit]
        Description=Reload kvm_intel to allow nested virtualization.

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/bin/sh -c 'modprobe -r kvm_intel && modprobe kvm_intel nested=1'
        ExecStop=/bin/sh -c 'modprobe -r kvm_intel && modprobe kvm_intel'
    # Setup taskcluster-worker
    - name:    taskcluster-worker.service
      command: start
      content: |
        [Unit]
        Description=taskcluster worker process
        Requires=papertrail.service docker.service kvm_intel_nested.service

        [Service]
        Restart=always
        ExecStart=/usr/bin/docker \
          run -p 443:443 --rm --privileged \
          --env-file /etc/taskcluster-worker-env.list \
          --name taskcluster-worker \
          taskcluster/tc-worker@sha256:1e44d165ef38ec85637778d2c413cdf2e27f3c99782e3585470593e3196085a1
        ExecStop=/usr/bin/docker kill taskcluster-worker

        [Install]
        WantedBy=multi-user.target
# Add file with environment variables for taskcluster-worker
write_files:
  - path:         /etc/taskcluster-worker-env.list
    permissions:  '0400'
    owner:        root
    content: |
      ENGINE=qemu
      TASKCLUSTER_CLIENT_ID=<client-id>
      TASKCLUSTER_ACCESS_TOKEN=<access-token>
      PORT=443
      PROVISIONER_ID=manual-packet
      WORKER_TYPE=tc-worker-qemu-v1
      WORKER_GROUP=manual-packet-sjc1
      WORKER_ID=machine-1
      PROJECT=tc-worker-qemu-v1
      DEBUG=*
