# Configuration file for tc-worker.Dockerfile
transforms:
  - env
  - secrets
  - packet
config:
  credentials:
    # Taskcluster credentials with scopes like:
    # - assume:project:taskcluster:worker-test-scopes
    # - secrets:get:project/taskcluster/taskcluster-worker/stateless-dns
    clientId:       {$env: TASKCLUSTER_CLIENT_ID}
    accessToken:    {$env: TASKCLUSTER_ACCESS_TOKEN}
  engine: qemu
  engines:
    qemu:
      maxConcurrency: 2
      imageFolder:    /mnt/images
      socketFolder:   /mnt/sockets
      machineOptions:
        maxMemory:    4096
  minimumDiskSpace:   10000000  # 10 GB
  minimumMemory:      1000000   # 1 GB
  monitor:
    logLevel:       debug
    project:        test-dummy-worker
  plugins:
    disabled:       [reboot]
    interactive:    {}
    artifacts:      {}
    env:            {}
    livelog:        {}
    maxruntime:     {}
    success:        {}
  temporaryFolder:  /mnt/tmp
  webHookServer:
    provider:           stateless-dns
    maxLifeCycle:       '4 days'
    serverIp:           {$packet: public-ipv4}
    serverPort:         {$env: PORT, type: number}
    networkInterface:   eth0
    exposedPort:        {$env: PORT, type: number}
    tlsCertificate:
      $secret:  project/taskcluster/taskcluster-worker/stateless-dns
      key:      certificate
    tlsKey:
      $secret:  project/taskcluster/taskcluster-worker/stateless-dns
      key:      tlsKey
    statelessDNSSecret:
      $secret:  project/taskcluster/taskcluster-worker/stateless-dns
      key:      secret
    statelessDNSDomain:
      $secret:  project/taskcluster/taskcluster-worker/stateless-dns
      key:      domain
  worker:
    concurrency:          2
    minimumReclaimDelay:  30
    pollingInterval:      5
    reclaimOffset:        300
    provisionerId:        {$env: PROVISIONER_ID}
    workerType:           {$env: WORKER_TYPE}
    workerGroup:          {$env: WORKER_GROUP}
    workerId:             {$env: WORKER_ID}
